echo on
set archive /tmp/hagrid
set plotwindowsize 12
load r379556-2.fits.fz
draw original
set maglimit 22
get cat dr2
get cat usno
plot cat dr2
plot cat usno
mask dr2
mask usno
mask border
set superpixelsize 25
make pixels
set spacinglimit 1
get pointings 50 top
get pointings -10 bottom
match
attachrband top
attachrband bottom
# clear
# draw original
plot object top
set colour b
plot object bottom
dump image {root}.png
dump top {root}.sources.fits fits 
dump bottom {root}.sky.fits fits 

